---
title: "Test Run"
author: "Dylan Stark"
output: html_document
---

```{r warning=FALSE,message=FALSE,results='hide'}
library(acs)
library(stringr)
```

```{r results='hide'}
myFileName <- "../key/key.txt"
myKey <- readChar(myFileName, file.info(myFileName)$size - 1)
api.key.install(myKey, file = "key.rda")
```

Installed key (``r myKey``).

Testing lookup:

```{r}
lookup <- acs.lookup(endyear = 2011,
                     span = 5,
                     dataset = "acs",
                     keyword = c("poverty", "workers"))
lookup@endyear
lookup@span
head(lookup@results)
```

Testing looking up geography:

```{r}
geo_lookup <- geo.lookup(state = "IL",
                         county = "Cook County")
geo_lookup
```

Testing getting geography:

```{r}
geo <- geo.make(state = "IL",
                county = "Cook County",
                tract = "*")
geo@geo.list[[1]]@name
```

Testing pulling table `B17014`:

```{r}
data <- acs.fetch(endyear = 2011,
                  span = 5,
                  geography = geo,
                  table.number = "B17014")
data@endyear
head(data@geography)
levels(data@acs.units)
```

Create data frame.
Each row corresponds to a tract within Cook County, IL.

```{r}
df <- data.frame(data@estimate)
summary(df)
```

Add tract information to data frame, and remove rownames.

```{r}
df$tract <- str_extract(rownames(df), "[\\d.]{1,7}")

rownames(df) <- NULL
```
